version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: italianos-forever-app
    container_name: italianos-forever-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network
    depends_on:
      - mysql
      - redis
      - mailhog

  mysql:
    image: mysql:5.7
    container_name: mysql_italianos_forever
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: italianos_forever_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_italianos_forever
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - mysql

  redis:
    image: redis:alpine
    container_name: redis_italianos_forever
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - app-network

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog_italianos_forever
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx_italianos_forever
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - app-network
    depends_on:
      - app

volumes:
  mysql-data:
    driver: local

networks:
  app-network:
    driver: bridge
